/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/research` | `/research`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/strategy` | `/strategy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trade` | `/trade`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workspace` | `/workspace`; params?: Router.UnknownInputParams; } | { pathname: `/library/import`; params?: Router.UnknownInputParams; } | { pathname: `/asset/[symbol]`, params: Router.UnknownInputParams & { symbol: string | number; } } | { pathname: `/library/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/strategy/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/account`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/research` | `/research`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/strategy` | `/strategy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trade` | `/trade`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workspace` | `/workspace`; params?: Router.UnknownOutputParams; } | { pathname: `/library/import`; params?: Router.UnknownOutputParams; } | { pathname: `/asset/[symbol]`, params: Router.UnknownOutputParams & { symbol: string; } } | { pathname: `/library/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/strategy/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/account${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/research${`?${string}` | `#${string}` | ''}` | `/research${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/strategy${`?${string}` | `#${string}` | ''}` | `/strategy${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trade${`?${string}` | `#${string}` | ''}` | `/trade${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workspace${`?${string}` | `#${string}` | ''}` | `/workspace${`?${string}` | `#${string}` | ''}` | `/library/import${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/research` | `/research`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/strategy` | `/strategy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trade` | `/trade`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workspace` | `/workspace`; params?: Router.UnknownInputParams; } | { pathname: `/library/import`; params?: Router.UnknownInputParams; } | `/asset/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/library/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/strategy/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/asset/[symbol]`, params: Router.UnknownInputParams & { symbol: string | number; } } | { pathname: `/library/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/strategy/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
